name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt  # Ensure no cache is used during installation

      - name: Run tests without coverage
        run:  PYTHONPATH=src pytest

          

      - name: Start SonarQube Docker container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
          sleep 30  # Wait for SonarQube to fully start

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"

      - name: Stop SonarQube Docker container
        run: |
          docker stop sonarqube
          docker rm sonarqube
